project_name: kubectl-open_svc
builds:
- main: ./cmd/kubectl-open_svc.go
  binary: kubectl-open_svc
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm
  - arm64
archives:
- name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  format: zip
  files:
  - LICENSE
  - README.md
  wrap_in_directory: false
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
krews:
- name: open-svc
  homepage: https://github.com/superbrothers/kubectl-open-svc-plugin
  description: |
    Open the Kubernetes URL(s) for the specified service in your browser.
    Unlike the `kubectl port-forward` command, this plugin makes services
    accessible via their ClusterIP.
  short_description: Open the Kubernetes URL(s) for the specified service in your browser.
  skip_upload: false
