apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: open-svc
spec:
  platforms:
  - {{addURIAndSha "https://github.com/superbrothers/kubectl-open-svc-plugin/releases/download/{{ .TagName }}/kubectl-open_svc-darwin-amd64.zip" .TagName }}
    bin: kubectl-open_svc
    files:
    - from: kubectl-open_svc
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        os: darwin
        arch: amd64
  - {{addURIAndSha "https://github.com/superbrothers/kubectl-open-svc-plugin/releases/download/{{ .TagName }}/kubectl-open_svc-darwin-arm64.zip" .TagName }}
    bin: kubectl-open_svc
    files:
    - from: kubectl-open_svc
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        os: darwin
        arch: arm64
  - {{addURIAndSha "https://github.com/superbrothers/kubectl-open-svc-plugin/releases/download/{{ .TagName }}/kubectl-open_svc-linux-amd64.zip" .TagName }}
    bin: kubectl-open_svc
    files:
    - from: kubectl-open_svc
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        os: linux
        arch: amd64
  - {{addURIAndSha "https://github.com/superbrothers/kubectl-open-svc-plugin/releases/download/{{ .TagName }}/kubectl-open_svc-linux-arm64.zip" .TagName }}
    bin: kubectl-open_svc
    files:
    - from: kubectl-open_svc
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        os: linux
        arch: arm64
  - {{addURIAndSha "https://github.com/superbrothers/kubectl-open-svc-plugin/releases/download/{{ .TagName }}/kubectl-open_svc-linux-arm.zip" .TagName }}
    bin: kubectl-open_svc
    files:
    - from: kubectl-open_svc
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        os: linux
        arch: arm
  - {{addURIAndSha "https://github.com/superbrothers/kubectl-open-svc-plugin/releases/download/{{ .TagName }}/kubectl-open_svc-windows-amd64.zip" .TagName }}
    bin: kubectl-open_svc.exe
    files:
    - from: kubectl-open_svc.exe
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        os: windows
        arch: amd64
  version: "{{ .TagName }}"
  shortDescription: Open the Kubernetes URL(s) for the specified service in your browser.
  description: |
    Open the Kubernetes URL(s) for the specified service in your browser.
    Unlike the `kubectl port-forward` command, this plugin makes services
    accessible via their ClusterIP.
  homepage: https://github.com/superbrothers/kubectl-open-svc-plugin
