apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: open-svc
spec:
  platforms:
  - uri: "https://github.com/superbrothers/kubectl-open-svc-plugin/releases/download/VERSION/kubectl-open_svc-darwin-amd64.zip"
    sha256: "DARWIN_SHA256"
    bin: kubectl-open_svc
    files:
    - from: kubectl-open_svc
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        os: darwin
        arch: amd64
  - uri: "https://github.com/superbrothers/kubectl-open-svc-plugin/releases/download/VERSION/kubectl-open_svc-linux-amd64.zip"
    sha256: "LINUX_SHA256"
    bin: kubectl-open_svc
    files:
    - from: kubectl-open_svc
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        os: linux
        arch: amd64
  version: "VERSION"
  shortDescription: Open the Kubernetes URL(s) for the specified service in your browser.
  description: |
    Open the Kubernetes URL(s) for the specified service in your browser.
    Unlike the `kubectl port-forward` command, this plugin makes services
    accessible via their ClusterIP.
  homepage: https://github.com/superbrothers/kubectl-open-svc-plugin
