name: Release

on:
  push:
    tags: ["v*"]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - run: make release
    - uses: softprops/action-gh-release@v1
      with:
        files: dist/!(config.yaml)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: rajatjindal/krew-release-bot@v0.0.46
      with:
        krew_template_file: dist/krew/open-svc.yaml
